// 注音符號資料：37 個符號（聲符 21、介音 3、韻符 13）
const BOPOMOFO_SYMBOLS = [
  { symbol: "ㄅ", category: "initial", word: "爸爸", emoji: "👨" },
  { symbol: "ㄆ", category: "initial", word: "皮球", emoji: "⚽" },
  { symbol: "ㄇ", category: "initial", word: "媽媽", emoji: "👩" },
  { symbol: "ㄈ", category: "initial", word: "飛機", emoji: "✈️" },
  { symbol: "ㄉ", category: "initial", word: "弟弟", emoji: "👦" },
  { symbol: "ㄊ", category: "initial", word: "兔子", emoji: "🐰" },
  { symbol: "ㄋ", category: "initial", word: "牛奶", emoji: "🥛" },
  { symbol: "ㄌ", category: "initial", word: "老虎", emoji: "🐯" },
  { symbol: "ㄍ", category: "initial", word: "狗狗", emoji: "🐶" },
  { symbol: "ㄎ", category: "initial", word: "褲子", emoji: "👖" },
  { symbol: "ㄏ", category: "initial", word: "河馬", emoji: "🦛" },
  { symbol: "ㄐ", category: "initial", word: "雞蛋", emoji: "🥚" },
  { symbol: "ㄑ", category: "initial", word: "汽車", emoji: "🚗" },
  { symbol: "ㄒ", category: "initial", word: "西瓜", emoji: "🍉" },
  { symbol: "ㄓ", category: "initial", word: "蜘蛛", emoji: "🕷️" },
  { symbol: "ㄔ", category: "initial", word: "吃飯", emoji: "🍚" },
  { symbol: "ㄕ", category: "initial", word: "獅子", emoji: "🦁" },
  { symbol: "ㄖ", category: "initial", word: "熱狗", emoji: "🌭" },
  { symbol: "ㄗ", category: "initial", word: "嘴巴", emoji: "👄" },
  { symbol: "ㄘ", category: "initial", word: "草莓", emoji: "🍓" },
  { symbol: "ㄙ", category: "initial", word: "松鼠", emoji: "🐿️" },
  { symbol: "ㄧ", category: "medial", word: "衣服", emoji: "👕" },
  { symbol: "ㄨ", category: "medial", word: "烏龜", emoji: "🐢" },
  { symbol: "ㄩ", category: "medial", word: "魚兒", emoji: "🐟" },
  { symbol: "ㄚ", category: "final", word: "阿嬤", emoji: "👵" },
  { symbol: "ㄛ", category: "final", word: "菠蘿", emoji: "🍍" },
  { symbol: "ㄜ", category: "final", word: "鵝", emoji: "🦢" },
  { symbol: "ㄝ", category: "final", word: "椰子", emoji: "🥥" },
  { symbol: "ㄞ", category: "final", word: "愛心", emoji: "❤️" },
  { symbol: "ㄟ", category: "final", word: "杯子", emoji: "🥤" },
  { symbol: "ㄠ", category: "final", word: "貓咪", emoji: "🐱" },
  { symbol: "ㄡ", category: "final", word: "球", emoji: "🏀" },
  { symbol: "ㄢ", category: "final", word: "安全", emoji: "🏠" },
  { symbol: "ㄣ", category: "final", word: "恩典", emoji: "🌟" },
  { symbol: "ㄤ", category: "final", word: "昂首", emoji: "🦒" },
  { symbol: "ㄥ", category: "final", word: "蜻蜓", emoji: "🐝" },
  { symbol: "ㄦ", category: "final", word: "兒子", emoji: "👶" },
];

// 拼音練習用：聲符卡 + 韻符卡 → 完整拼音與例字
const PINYIN_COMBOS = [
  { initial: "ㄅ", final: "ㄚˋ", word: "爸", emoji: "👨" },
  { initial: "ㄇ", final: "ㄚ", word: "媽", emoji: "👩" },
  { initial: "ㄍ", final: "ㄡˇ", word: "狗", emoji: "🐶" },
  { initial: "ㄇ", final: "ㄠ", word: "貓", emoji: "🐱" },
  { initial: "ㄏ", final: "ㄨˇ", word: "虎", emoji: "🐯" },
  { initial: "ㄊ", final: "ㄨˋ", word: "兔", emoji: "🐰" },
  { initial: "ㄐ", final: "ㄧ", word: "雞", emoji: "🐔" },
  { initial: "ㄕ", final: "ㄨˇ", word: "鼠", emoji: "🐭" },
  { initial: "ㄋ", final: "ㄞˇ", word: "奶", emoji: "🥛" },
  { initial: "ㄏ", final: "ㄞˊ", word: "孩", emoji: "🧒" },
  { initial: "ㄒ", final: "ㄧ", word: "西", emoji: "🍉" },
  { initial: "ㄓ", final: "ㄨ", word: "豬", emoji: "🐷" },
  { initial: "ㄋ", final: "ㄩˇ", word: "女", emoji: "👧" },
  { initial: "ㄈ", final: "ㄟ", word: "飛", emoji: "✈️" },
  { initial: "ㄏ", final: "ㄨㄚ", word: "花", emoji: "🌸" },
  { initial: "ㄒ", final: "ㄧㄠˇ", word: "小", emoji: "🤏" },
  { initial: "ㄉ", final: "ㄢˋ", word: "蛋", emoji: "🥚" },
  { initial: "ㄋ", final: "ㄧㄡˊ", word: "牛", emoji: "🐮" },
  { initial: "ㄕ", final: "ㄨˋ", word: "樹", emoji: "🌳" },
  { initial: "ㄍ", final: "ㄨㄚ", word: "瓜", emoji: "🍈" },
  { initial: "ㄕ", final: "ㄜˊ", word: "蛇", emoji: "🐍" },
  { initial: "ㄒ", final: "ㄩㄥˊ", word: "熊", emoji: "🐻" },
];

// 聲調辨識用：同一拼寫、四種聲調的詞語組合
const TONE_SETS = [
  // ── 每組的 word 第一個字必須對應 spelling + mark 的聲調 ──
  { spelling: "ㄇㄚ", tones: [
    { mark: "",  word: "媽媽", emoji: "👩" },
    { mark: "ˊ", word: "麻煩", emoji: "😣" },
    { mark: "ˇ", word: "馬路", emoji: "🐴" },
    { mark: "ˋ", word: "罵人", emoji: "😠" },
  ]},
  { spelling: "ㄧ", tones: [
    { mark: "",  word: "衣服", emoji: "👕" },
    { mark: "ˊ", word: "移動", emoji: "🚚" },
    { mark: "ˇ", word: "椅子", emoji: "🪑" },
    { mark: "ˋ", word: "意思", emoji: "💭" },
  ]},
  { spelling: "ㄨ", tones: [
    { mark: "",  word: "烏龜", emoji: "🐢" },
    { mark: "ˊ", word: "無聊", emoji: "😴" },
    { mark: "ˇ", word: "五個", emoji: "5️⃣" },
    { mark: "ˋ", word: "物品", emoji: "📦" },
  ]},
  { spelling: "ㄊㄤ", tones: [
    { mark: "",  word: "湯麵", emoji: "🍲" },
    { mark: "ˊ", word: "糖果", emoji: "🍬" },
    { mark: "ˇ", word: "躺下", emoji: "🛌" },
    { mark: "ˋ", word: "燙傷", emoji: "🥵" },
  ]},
  { spelling: "ㄈㄢ", tones: [
    { mark: "",  word: "翻書", emoji: "📚" },
    { mark: "ˊ", word: "煩惱", emoji: "😩" },
    { mark: "ˇ", word: "反對", emoji: "↩️" },
    { mark: "ˋ", word: "飯糰", emoji: "🍙" },
  ]},
  { spelling: "ㄒㄧ", tones: [
    { mark: "",  word: "西瓜", emoji: "🍉" },
    { mark: "ˊ", word: "習字", emoji: "📝" },
    { mark: "ˇ", word: "喜歡", emoji: "😊" },
    { mark: "ˋ", word: "細心", emoji: "🔍" },
  ]},
  { spelling: "ㄅㄚ", tones: [
    { mark: "",  word: "八個", emoji: "8️⃣" },
    { mark: "ˊ", word: "拔河", emoji: "🪢" },
    { mark: "ˇ", word: "靶心", emoji: "🎯" },
    { mark: "ˋ", word: "爸爸", emoji: "👨" },
  ]},
  { spelling: "ㄉㄚ", tones: [
    { mark: "",  word: "搭車", emoji: "🚌" },
    { mark: "ˊ", word: "答案", emoji: "📋" },
    { mark: "ˇ", word: "打球", emoji: "⚾" },
    { mark: "ˋ", word: "大人", emoji: "🧑" },
  ]},
  { spelling: "ㄩ", tones: [
    { mark: "",  word: "迂迴", emoji: "🔄" },
    { mark: "ˊ", word: "魚兒", emoji: "🐟" },
    { mark: "ˇ", word: "雨傘", emoji: "☂️" },
    { mark: "ˋ", word: "玉米", emoji: "🌽" },
  ]},
  { spelling: "ㄍㄨㄛ", tones: [
    { mark: "",  word: "鍋子", emoji: "🫕" },
    { mark: "ˊ", word: "國家", emoji: "🏳️" },
    { mark: "ˇ", word: "果汁", emoji: "🧃" },
    { mark: "ˋ", word: "過年", emoji: "🎆" },
  ]},
  { spelling: "ㄐㄧ", tones: [
    { mark: "",  word: "雞蛋", emoji: "🐔" },
    { mark: "ˊ", word: "及格", emoji: "✅" },
    { mark: "ˇ", word: "幾個", emoji: "❓" },
    { mark: "ˋ", word: "記住", emoji: "🧠" },
  ]},
  { spelling: "ㄓㄨ", tones: [
    { mark: "",  word: "豬肉", emoji: "🐷" },
    { mark: "ˊ", word: "竹子", emoji: "🎋" },
    { mark: "ˇ", word: "主人", emoji: "👑" },
    { mark: "ˋ", word: "住家", emoji: "🏡" },
  ]},
  { spelling: "ㄎㄜ", tones: [
    { mark: "",  word: "科學", emoji: "🔬" },
    { mark: "ˊ", word: "殼", emoji: "🥚" },
    { mark: "ˇ", word: "口渴", emoji: "🥤" },
    { mark: "ˋ", word: "上課", emoji: "🏫" },
  ]},
  { spelling: "ㄔㄜ", tones: [
    { mark: "",  word: "車子", emoji: "🚗" },
    { mark: "ˊ", word: "扯斷", emoji: "💥" },
    { mark: "ˇ", word: "扯", emoji: "🤥" },
    { mark: "ˋ", word: "徹底", emoji: "✨" },
  ]},
  { spelling: "ㄋㄧㄡ", tones: [
    { mark: "",  word: "牛奶", emoji: "🥛" },
    { mark: "ˊ", word: "牛肉", emoji: "🐂" },
    { mark: "ˇ", word: "扭動", emoji: "💃" },
    { mark: "ˋ", word: "按鈕", emoji: "🔘" },
  ]},
  { spelling: "ㄈㄟ", tones: [
    { mark: "",  word: "飛機", emoji: "✈️" },
    { mark: "ˊ", word: "肥胖", emoji: "🐷" },
    { mark: "ˇ", word: "匪徒", emoji: "🦹" },
    { mark: "ˋ", word: "廢紙", emoji: "🗑️" },
  ]},
];

// 字首範例詞語的額外候選（增加「看圖找字頭」「記憶配對」的圖案多樣性）
const INITIAL_WORD_EXTRAS = {
  "ㄅ": [{ word: "杯子", emoji: "🥤" }, { word: "蝙蝠", emoji: "🦇" }, { word: "包子", emoji: "🥟" }, { word: "冰淇淋", emoji: "🍦" }, { word: "斑馬", emoji: "🦓" }, { word: "筆", emoji: "🖊️" }],
  "ㄆ": [{ word: "葡萄", emoji: "🍇" }, { word: "蘋果", emoji: "🍎" }, { word: "盤子", emoji: "🍽️" }, { word: "螃蟹", emoji: "🦀" }, { word: "跑步", emoji: "🏃" }],
  "ㄇ": [{ word: "貓咪", emoji: "🐱" }, { word: "帽子", emoji: "🎩" }, { word: "馬", emoji: "🐴" }, { word: "麵包", emoji: "🍞" }, { word: "芒果", emoji: "🥭" }],
  "ㄈ": [{ word: "蜂蜜", emoji: "🍯" }, { word: "房子", emoji: "🏠" }, { word: "風車", emoji: "🎐" }, { word: "斧頭", emoji: "🪓" }, { word: "番茄", emoji: "🍅" }],
  "ㄉ": [{ word: "蛋糕", emoji: "🎂" }, { word: "燈泡", emoji: "💡" }, { word: "大象", emoji: "🐘" }, { word: "刀子", emoji: "🔪" }, { word: "電視", emoji: "📺" }],
  "ㄊ": [{ word: "太陽", emoji: "☀️" }, { word: "糖果", emoji: "🍬" }, { word: "天鵝", emoji: "🦢" }, { word: "拖鞋", emoji: "🩴" }, { word: "跳舞", emoji: "💃" }],
  "ㄋ": [{ word: "鳥",   emoji: "🐦" }, { word: "檸檬", emoji: "🍋" }, { word: "男孩", emoji: "👦" }, { word: "南瓜", emoji: "🎃" }, { word: "鈕扣", emoji: "🔘" }],
  "ㄌ": [{ word: "籃球", emoji: "🏀" }, { word: "梨子", emoji: "🍐" }, { word: "禮物", emoji: "🎁" }, { word: "鹿", emoji: "🦌" }, { word: "輪胎", emoji: "🛞" }],
  "ㄍ": [{ word: "鴿子", emoji: "🕊️" }, { word: "鼓",   emoji: "🥁" }, { word: "公雞", emoji: "🐓" }, { word: "狗", emoji: "🐕" }, { word: "骨頭", emoji: "🦴" }],
  "ㄎ": [{ word: "咖啡", emoji: "☕" }, { word: "可樂", emoji: "🥤" }, { word: "恐龍", emoji: "🦖" }, { word: "孔雀", emoji: "🦚" }, { word: "烤肉", emoji: "🥩" }],
  "ㄏ": [{ word: "花",   emoji: "🌸" }, { word: "猴子", emoji: "🐵" }, { word: "紅綠燈", emoji: "🚥" }, { word: "蝴蝶", emoji: "🦋" }, { word: "火車", emoji: "🚂" }],
  "ㄐ": [{ word: "腳",   emoji: "🦶" }, { word: "橘子", emoji: "🍊" }, { word: "剪刀", emoji: "✂️" }, { word: "警察", emoji: "👮" }, { word: "機器人", emoji: "🤖" }],
  "ㄑ": [{ word: "企鵝", emoji: "🐧" }, { word: "氣球", emoji: "🎈" }, { word: "鉛筆", emoji: "✏️" }, { word: "青蛙", emoji: "🐸" }, { word: "橋", emoji: "🌉" }],
  "ㄒ": [{ word: "鞋子", emoji: "👟" }, { word: "熊",   emoji: "🐻" }, { word: "香蕉", emoji: "🍌" }, { word: "星星", emoji: "⭐" }, { word: "信封", emoji: "✉️" }],
  "ㄓ": [{ word: "豬",   emoji: "🐷" }, { word: "竹子", emoji: "🎋" }, { word: "帳篷", emoji: "⛺" }, { word: "直昇機", emoji: "🚁" }, { word: "章魚", emoji: "🐙" }],
  "ㄔ": [{ word: "唱歌", emoji: "🎤" }, { word: "尺",   emoji: "📏" }, { word: "車子", emoji: "🚗" }, { word: "蟲", emoji: "🐛" }, { word: "翅膀", emoji: "🪽" }],
  "ㄕ": [{ word: "樹",   emoji: "🌳" }, { word: "手",   emoji: "🖐️" }, { word: "書", emoji: "📖" }, { word: "獅子", emoji: "🦁" }, { word: "沙發", emoji: "🛋️" }],
  "ㄖ": [{ word: "肉",   emoji: "🍖" }, { word: "日出", emoji: "🌅" }, { word: "忍者", emoji: "🥷" }, { word: "人", emoji: "🧑" }, { word: "軟糖", emoji: "🍬" }],
  "ㄗ": [{ word: "走路", emoji: "🚶" }, { word: "足球", emoji: "⚽" }, { word: "紫色", emoji: "🟣" }, { word: "鑽石", emoji: "💎" }, { word: "字典", emoji: "📚" }],
  "ㄘ": [{ word: "廁所", emoji: "🚽" }, { word: "彩虹", emoji: "🌈" }, { word: "刺蝟", emoji: "🦔" }, { word: "草莓", emoji: "🍓" }, { word: "蔥", emoji: "🧅" }],
  "ㄙ": [{ word: "傘",   emoji: "☂️" }, { word: "送禮", emoji: "🎁" }, { word: "森林", emoji: "🌲" }, { word: "鎖", emoji: "🔒" }, { word: "色彩", emoji: "🎨" }],
};

const OTHER_WORD_EXTRAS = {
  "ㄧ": [{ word: "一", emoji: "1️⃣" }, { word: "醫生", emoji: "👨‍⚕️" }, { word: "衣服", emoji: "👕" }, { word: "椅子", emoji: "🪑" }, { word: "音樂", emoji: "🎵" }],
  "ㄨ": [{ word: "五", emoji: "5️⃣" }, { word: "蝸牛", emoji: "🐌" }, { word: "烏鴉", emoji: "🐦‍⬛" }, { word: "襪子", emoji: "🧦" }, { word: "網子", emoji: "🕸️" }],
  "ㄩ": [{ word: "月亮", emoji: "🌙" }, { word: "雨傘", emoji: "☂️" }, { word: "玉米", emoji: "🌽" }, { word: "魚", emoji: "🐟" }, { word: "浴缸", emoji: "🛁" }],
  "ㄚ": [{ word: "鴨子", emoji: "🦆" }, { word: "牙齒", emoji: "🦷" }, { word: "啞鈴", emoji: "🏋️" }, { word: "蠟筆", emoji: "🖍️" }, { word: "螞蟻", emoji: "🐜" }],
  "ㄛ": [{ word: "火鍋", emoji: "🍲" }, { word: "喔", emoji: "😲" }, { word: "駱駝", emoji: "🐪" }, { word: "蘋果", emoji: "🍎" }],
  "ㄜ": [{ word: "鱷魚", emoji: "🐊" }, { word: "肚子餓", emoji: "🤤" }, { word: "天鵝", emoji: "🦢" }, { word: "蛇", emoji: "🐍" }, { word: "車子", emoji: "🚗" }],
  "ㄝ": [{ word: "鞋子", emoji: "👞" }, { word: "葉子", emoji: "🍃" }, { word: "爺爺", emoji: "👴" }, { word: "蝴蝶", emoji: "🦋" }],
  "ㄞ": [{ word: "矮子", emoji: "🧍" }, { word: "海邊", emoji: "🏖️" }, { word: "愛心", emoji: "💖" }, { word: "麥克風", emoji: "🎤" }, { word: "拍手", emoji: "👏" }],
  "ㄟ": [{ word: "飛盤", emoji: "🥏" }, { word: "黑板", emoji: "⬛" }, { word: "飛機", emoji: "✈️" }, { word: "草莓", emoji: "🍓" }, { word: "水杯", emoji: "🥤" }],
  "ㄠ": [{ word: "桃子", emoji: "🍑" }, { word: "鑰匙", emoji: "🔑" }, { word: "手錶", emoji: "⌚" }, { word: "貓咪", emoji: "🐈" }, { word: "背包", emoji: "🎒" }],
  "ㄡ": [{ word: "海鷗", emoji: "🕊️" }, { word: "猴子", emoji: "🐒" }, { word: "狗", emoji: "🐕" }, { word: "球", emoji: "⚽" }, { word: "海牛", emoji: "🦭" }],
  "ㄢ": [{ word: "山", emoji: "⛰️" }, { word: "看書", emoji: "📖" }, { word: "雨傘", emoji: "☂️" }, { word: "船", emoji: "🚢" }, { word: "飯", emoji: "🍚" }],
  "ㄣ": [{ word: "門", emoji: "🚪" }, { word: "森林", emoji: "🌲" }, { word: "神仙", emoji: "🧚" }, { word: "盆栽", emoji: "🪴" }, { word: "灰塵", emoji: "💨" }],
  "ㄤ": [{ word: "螳螂", emoji: "🦗" }, { word: "胖子", emoji: "🧍‍♂️" }, { word: "鋼琴", emoji: "🎹" }, { word: "糖果", emoji: "🍬" }, { word: "湯", emoji: "🥣" }],
  "ㄥ": [{ word: "風箏", emoji: "🪁" }, { word: "企鵝", emoji: "🐧" }, { word: "蜜蜂", emoji: "🐝" }, { word: "城堡", emoji: "🏰" }, { word: "燈", emoji: "💡" }],
  "ㄦ": [{ word: "耳朵", emoji: "👂" }, { word: "兒童", emoji: "🧒" }, { word: "兒子", emoji: "👦" }, { word: "鳥兒", emoji: "🐦" }],
};
