// 注音符號資料：37 個符號（聲符 21、介音 3、韻符 13）
const BOPOMOFO_SYMBOLS = [
  { symbol: "ㄅ", category: "initial", word: "爸爸", emoji: "👨" },
  { symbol: "ㄆ", category: "initial", word: "皮球", emoji: "⚽" },
  { symbol: "ㄇ", category: "initial", word: "媽媽", emoji: "👩" },
  { symbol: "ㄈ", category: "initial", word: "飛機", emoji: "✈️" },
  { symbol: "ㄉ", category: "initial", word: "弟弟", emoji: "👦" },
  { symbol: "ㄊ", category: "initial", word: "兔子", emoji: "🐰" },
  { symbol: "ㄋ", category: "initial", word: "牛奶", emoji: "🥛" },
  { symbol: "ㄌ", category: "initial", word: "老虎", emoji: "🐯" },
  { symbol: "ㄍ", category: "initial", word: "狗狗", emoji: "🐶" },
  { symbol: "ㄎ", category: "initial", word: "褲子", emoji: "👖" },
  { symbol: "ㄏ", category: "initial", word: "河馬", emoji: "🦛" },
  { symbol: "ㄐ", category: "initial", word: "雞蛋", emoji: "🥚" },
  { symbol: "ㄑ", category: "initial", word: "汽車", emoji: "🚗" },
  { symbol: "ㄒ", category: "initial", word: "西瓜", emoji: "🍉" },
  { symbol: "ㄓ", category: "initial", word: "蜘蛛", emoji: "🕷️" },
  { symbol: "ㄔ", category: "initial", word: "吃飯", emoji: "🍚" },
  { symbol: "ㄕ", category: "initial", word: "獅子", emoji: "🦁" },
  { symbol: "ㄖ", category: "initial", word: "熱狗", emoji: "🌭" },
  { symbol: "ㄗ", category: "initial", word: "桌子", emoji: "🪑" },
  { symbol: "ㄘ", category: "initial", word: "草莓", emoji: "🍓" },
  { symbol: "ㄙ", category: "initial", word: "松鼠", emoji: "🐿️" },
  { symbol: "ㄧ", category: "medial", word: "衣服", emoji: "👕" },
  { symbol: "ㄨ", category: "medial", word: "烏龜", emoji: "🐢" },
  { symbol: "ㄩ", category: "medial", word: "魚兒", emoji: "🐟" },
  { symbol: "ㄚ", category: "final", word: "阿嬤", emoji: "👵" },
  { symbol: "ㄛ", category: "final", word: "菠蘿", emoji: "🍍" },
  { symbol: "ㄜ", category: "final", word: "鵝", emoji: "🦢" },
  { symbol: "ㄝ", category: "final", word: "椰子", emoji: "🥥" },
  { symbol: "ㄞ", category: "final", word: "愛心", emoji: "❤️" },
  { symbol: "ㄟ", category: "final", word: "杯子", emoji: "🥤" },
  { symbol: "ㄠ", category: "final", word: "貓咪", emoji: "🐱" },
  { symbol: "ㄡ", category: "final", word: "球", emoji: "🏀" },
  { symbol: "ㄢ", category: "final", word: "安全", emoji: "🏠" },
  { symbol: "ㄣ", category: "final", word: "恩典", emoji: "🌟" },
  { symbol: "ㄤ", category: "final", word: "昂首", emoji: "🦒" },
  { symbol: "ㄥ", category: "final", word: "蜻蜓", emoji: "🐝" },
  { symbol: "ㄦ", category: "final", word: "兒子", emoji: "👶" },
];

// 拼音練習用：聲符卡 + 韻符卡 → 完整拼音與例字
const PINYIN_COMBOS = [
  { initial: "ㄅ", final: "ㄚˋ", word: "爸", emoji: "👨" },
  { initial: "ㄇ", final: "ㄚ", word: "媽", emoji: "👩" },
  { initial: "ㄍ", final: "ㄡˇ", word: "狗", emoji: "🐶" },
  { initial: "ㄇ", final: "ㄠ", word: "貓", emoji: "🐱" },
  { initial: "ㄏ", final: "ㄨˇ", word: "虎", emoji: "🐯" },
  { initial: "ㄊ", final: "ㄨˋ", word: "兔", emoji: "🐰" },
  { initial: "ㄐ", final: "ㄧ", word: "雞", emoji: "🐔" },
  { initial: "ㄕ", final: "ㄨˇ", word: "鼠", emoji: "🐭" },
  { initial: "ㄋ", final: "ㄞˇ", word: "奶", emoji: "🥛" },
  { initial: "ㄏ", final: "ㄞˊ", word: "孩", emoji: "🧒" },
  { initial: "ㄒ", final: "ㄧ", word: "西", emoji: "🍉" },
  { initial: "ㄓ", final: "ㄨ", word: "豬", emoji: "🐷" },
  { initial: "ㄋ", final: "ㄩˇ", word: "女", emoji: "👧" },
  { initial: "ㄈ", final: "ㄟ", word: "飛", emoji: "✈️" },
  { initial: "ㄏ", final: "ㄨㄚ", word: "花", emoji: "🌸" },
  { initial: "ㄒ", final: "ㄧㄠˇ", word: "小", emoji: "🤏" },
  { initial: "ㄉ", final: "ㄢˋ", word: "蛋", emoji: "🥚" },
  { initial: "ㄋ", final: "ㄧㄡˊ", word: "牛", emoji: "🐮" },
  { initial: "ㄕ", final: "ㄨˋ", word: "樹", emoji: "🌳" },
  { initial: "ㄍ", final: "ㄨㄚ", word: "瓜", emoji: "🍈" },
  { initial: "ㄕ", final: "ㄜˊ", word: "蛇", emoji: "🐍" },
  { initial: "ㄒ", final: "ㄩㄥˊ", word: "熊", emoji: "🐻" },
];
