// 注音符號資料：37 個符號（聲符 21、介音 3、韻符 13）
const BOPOMOFO_SYMBOLS = [
  { symbol: "ㄅ", category: "initial", word: "爸爸", emoji: "👨" },
  { symbol: "ㄆ", category: "initial", word: "皮球", emoji: "⚽" },
  { symbol: "ㄇ", category: "initial", word: "媽媽", emoji: "👩" },
  { symbol: "ㄈ", category: "initial", word: "飛機", emoji: "✈️" },
  { symbol: "ㄉ", category: "initial", word: "弟弟", emoji: "👦" },
  { symbol: "ㄊ", category: "initial", word: "兔子", emoji: "🐰" },
  { symbol: "ㄋ", category: "initial", word: "牛奶", emoji: "🥛" },
  { symbol: "ㄌ", category: "initial", word: "老虎", emoji: "🐯" },
  { symbol: "ㄍ", category: "initial", word: "狗狗", emoji: "🐶" },
  { symbol: "ㄎ", category: "initial", word: "褲子", emoji: "👖" },
  { symbol: "ㄏ", category: "initial", word: "河馬", emoji: "🦛" },
  { symbol: "ㄐ", category: "initial", word: "雞蛋", emoji: "🥚" },
  { symbol: "ㄑ", category: "initial", word: "汽車", emoji: "🚗" },
  { symbol: "ㄒ", category: "initial", word: "西瓜", emoji: "🍉" },
  { symbol: "ㄓ", category: "initial", word: "蜘蛛", emoji: "🕷️" },
  { symbol: "ㄔ", category: "initial", word: "吃飯", emoji: "🍚" },
  { symbol: "ㄕ", category: "initial", word: "獅子", emoji: "🦁" },
  { symbol: "ㄖ", category: "initial", word: "熱狗", emoji: "🌭" },
  { symbol: "ㄗ", category: "initial", word: "嘴巴", emoji: "👄" },
  { symbol: "ㄘ", category: "initial", word: "草莓", emoji: "🍓" },
  { symbol: "ㄙ", category: "initial", word: "松鼠", emoji: "🐿️" },
  { symbol: "ㄧ", category: "medial", word: "衣服", emoji: "👕" },
  { symbol: "ㄨ", category: "medial", word: "烏龜", emoji: "🐢" },
  { symbol: "ㄩ", category: "medial", word: "魚兒", emoji: "🐟" },
  { symbol: "ㄚ", category: "final", word: "阿嬤", emoji: "👵" },
  { symbol: "ㄛ", category: "final", word: "菠蘿", emoji: "🍍" },
  { symbol: "ㄜ", category: "final", word: "鵝", emoji: "🦢" },
  { symbol: "ㄝ", category: "final", word: "椰子", emoji: "🥥" },
  { symbol: "ㄞ", category: "final", word: "愛心", emoji: "❤️" },
  { symbol: "ㄟ", category: "final", word: "杯子", emoji: "🥤" },
  { symbol: "ㄠ", category: "final", word: "貓咪", emoji: "🐱" },
  { symbol: "ㄡ", category: "final", word: "球", emoji: "🏀" },
  { symbol: "ㄢ", category: "final", word: "安全", emoji: "🏠" },
  { symbol: "ㄣ", category: "final", word: "恩典", emoji: "🌟" },
  { symbol: "ㄤ", category: "final", word: "昂首", emoji: "🦒" },
  { symbol: "ㄥ", category: "final", word: "蜻蜓", emoji: "🐝" },
  { symbol: "ㄦ", category: "final", word: "兒子", emoji: "👶" },
];

// 拼音練習用：聲符卡 + 韻符卡 → 完整拼音與例字
const PINYIN_COMBOS = [
  { initial: "ㄅ", final: "ㄚˋ", word: "爸", emoji: "👨" },
  { initial: "ㄇ", final: "ㄚ", word: "媽", emoji: "👩" },
  { initial: "ㄍ", final: "ㄡˇ", word: "狗", emoji: "🐶" },
  { initial: "ㄇ", final: "ㄠ", word: "貓", emoji: "🐱" },
  { initial: "ㄏ", final: "ㄨˇ", word: "虎", emoji: "🐯" },
  { initial: "ㄊ", final: "ㄨˋ", word: "兔", emoji: "🐰" },
  { initial: "ㄐ", final: "ㄧ", word: "雞", emoji: "🐔" },
  { initial: "ㄕ", final: "ㄨˇ", word: "鼠", emoji: "🐭" },
  { initial: "ㄋ", final: "ㄞˇ", word: "奶", emoji: "🥛" },
  { initial: "ㄏ", final: "ㄞˊ", word: "孩", emoji: "🧒" },
  { initial: "ㄒ", final: "ㄧ", word: "西", emoji: "🍉" },
  { initial: "ㄓ", final: "ㄨ", word: "豬", emoji: "🐷" },
  { initial: "ㄋ", final: "ㄩˇ", word: "女", emoji: "👧" },
  { initial: "ㄈ", final: "ㄟ", word: "飛", emoji: "✈️" },
  { initial: "ㄏ", final: "ㄨㄚ", word: "花", emoji: "🌸" },
  { initial: "ㄒ", final: "ㄧㄠˇ", word: "小", emoji: "🤏" },
  { initial: "ㄉ", final: "ㄢˋ", word: "蛋", emoji: "🥚" },
  { initial: "ㄋ", final: "ㄧㄡˊ", word: "牛", emoji: "🐮" },
  { initial: "ㄕ", final: "ㄨˋ", word: "樹", emoji: "🌳" },
  { initial: "ㄍ", final: "ㄨㄚ", word: "瓜", emoji: "🍈" },
  { initial: "ㄕ", final: "ㄜˊ", word: "蛇", emoji: "🐍" },
  { initial: "ㄒ", final: "ㄩㄥˊ", word: "熊", emoji: "🐻" },
  { initial: "ㄇ", final: "ㄚˇ", word: "馬", emoji: "🐴" },
  { initial: "ㄧ", final: "ㄤˊ", word: "羊", emoji: "🐑" },
  { initial: "ㄏ", final: "ㄡˊ", word: "猴", emoji: "🐒" },
  { initial: "ㄌ", final: "ㄨˋ", word: "鹿", emoji: "🦌" },
  { initial: "ㄍ", final: "ㄨㄟ", word: "龜", emoji: "🐢" },
  { initial: "ㄩ", final: "ˊ", word: "魚", emoji: "🐟" },
  { initial: "ㄒ", final: "ㄧㄚ", word: "蝦", emoji: "🦐" },
  { initial: "ㄒ", final: "ㄧㄝˋ", word: "蟹", emoji: "🦀" },
  { initial: "ㄋ", final: "ㄧㄠˇ", word: "鳥", emoji: "🐦" },
  { initial: "ㄜ", final: "ˊ", word: "鵝", emoji: "🦢" },
  { initial: "ㄧ", final: "ㄚ", word: "鴨", emoji: "🦆" },
  { initial: "ㄔ", final: "ㄨㄥˊ", word: "蟲", emoji: "🐛" },
  { initial: "ㄈ", final: "ㄥ", word: "蜂", emoji: "🐝" },
  { initial: "ㄧ", final: "ㄝˋ", word: "葉", emoji: "🍃" },
  { initial: "ㄘ", final: "ㄠˇ", word: "草", emoji: "🌿" },
  { initial: "ㄕ", final: "ㄨㄟˇ", word: "水", emoji: "💧" },
  { initial: "ㄏ", final: "ㄨㄛˇ", word: "火", emoji: "🔥" },
  { initial: "ㄕ", final: "ㄢ", word: "山", emoji: "⛰️" },
  { initial: "ㄕ", final: "ˊ", word: "石", emoji: "🪨" },
  { initial: "ㄩ", final: "ㄣˊ", word: "雲", emoji: "☁️" },
  { initial: "ㄩ", final: "ˇ", word: "雨", emoji: "🌧️" },
  { initial: "ㄒ", final: "ㄩㄝˇ", word: "雪", emoji: "❄️" },
  { initial: "ㄈ", final: "ㄥ", word: "風", emoji: "💨" },
  { initial: "ㄉ", final: "ㄧㄢˋ", word: "電", emoji: "⚡" },
  { initial: "ㄖ", final: "ˋ", word: "日", emoji: "☀️" },
  { initial: "ㄩ", final: "ㄝˋ", word: "月", emoji: "🌙" },
  { initial: "ㄒ", final: "ㄧㄥ", word: "星", emoji: "⭐" },
  { initial: "ㄔ", final: "ㄜ", word: "車", emoji: "🚗" },
  { initial: "ㄔ", final: "ㄨㄢˊ", word: "船", emoji: "🚢" },
  { initial: "ㄕ", final: "ㄨ", word: "書", emoji: "📚" },
  { initial: "ㄅ", final: "ㄧˇ", word: "筆", emoji: "🖊️" },
  { initial: "ㄓ", final: "ˇ", word: "紙", emoji: "📄" },
  { initial: "ㄇ", final: "ㄣˊ", word: "門", emoji: "🚪" },
  { initial: "ㄔ", final: "ㄨㄤ", word: "窗", emoji: "🪟" },
  { initial: "ㄔ", final: "ㄨㄤˊ", word: "床", emoji: "🛏️" },
  { initial: "ㄉ", final: "ㄥ", word: "燈", emoji: "💡" },
  { initial: "ㄅ", final: "ㄟ", word: "杯", emoji: "☕" },
  { initial: "ㄆ", final: "ㄢˊ", word: "盤", emoji: "🍽️" },
  { initial: "ㄨ", final: "ㄢˇ", word: "碗", emoji: "🥣" },
  { initial: "ㄍ", final: "ㄨㄛ", word: "鍋", emoji: "🍲" },
  { initial: "ㄖ", final: "ㄡˋ", word: "肉", emoji: "🥩" },
  { initial: "ㄈ", final: "ㄢˋ", word: "飯", emoji: "🍚" },
  { initial: "ㄇ", final: "ㄧㄢˋ", word: "麵", emoji: "🍜" },
  { initial: "ㄊ", final: "ㄤ", word: "湯", emoji: "🥣" },
  { initial: "ㄅ", final: "ㄧㄥ", word: "冰", emoji: "🧊" },
  { initial: "ㄊ", final: "ㄤˊ", word: "糖", emoji: "🍬" },
  { initial: "ㄧ", final: "ㄠˋ", word: "藥", emoji: "💊" },
  { initial: "ㄒ", final: "ㄧㄝˊ", word: "鞋", emoji: "👞" },
  { initial: "ㄇ", final: "ㄠˋ", word: "帽", emoji: "🎩" },
  { initial: "ㄑ", final: "ㄩㄣˊ", word: "裙", emoji: "👗" },
  { initial: "ㄎ", final: "ㄨˋ", word: "褲", emoji: "👖" },
  { initial: "ㄨ", final: "ㄚˋ", word: "襪", emoji: "🧦" },
  { initial: "ㄕ", final: "ㄡˇ", word: "手", emoji: "🖐️" },
  { initial: "ㄗ", final: "ㄨˊ", word: "足", emoji: "🦶" },
  { initial: "ㄧ", final: "ㄢˇ", word: "眼", emoji: "👁️" },
  { initial: "ㄦ", final: "ˇ", word: "耳", emoji: "👂" },
  { initial: "ㄎ", final: "ㄡˇ", word: "口", emoji: "👄" },
  { initial: "ㄧ", final: "ㄚˊ", word: "牙", emoji: "🦷" },
  { initial: "ㄒ", final: "ㄧㄣ", word: "心", emoji: "❤️" },
  { initial: "ㄏ", final: "ㄨㄥˊ", word: "紅", emoji: "🟥" },
  { initial: "ㄏ", final: "ㄨㄤˊ", word: "黃", emoji: "🟨" },
  { initial: "ㄌ", final: "ㄩˋ", word: "綠", emoji: "🟩" },
  { initial: "ㄌ", final: "ㄢˊ", word: "藍", emoji: "🟦" },
  { initial: "ㄅ", final: "ㄞˊ", word: "白", emoji: "⬜" },
  { initial: "ㄏ", final: "ㄟ", word: "黑", emoji: "⬛" },
  { initial: "ㄔ", final: "ㄚˊ", word: "茶", emoji: "🍵" },
  { initial: "ㄍ", final: "ㄨㄛˇ", word: "果", emoji: "🍎" },
  { initial: "ㄕ", final: "ㄨㄟˇ", word: "水", emoji: "💧" },
  { initial: "ㄅ", final: "ㄠ", word: "包", emoji: "🎒" },
  { initial: "ㄉ", final: "ㄡˋ", word: "豆", emoji: "🫘" },
  { initial: "ㄇ", final: "ㄧˇ", word: "米", emoji: "🌾" },
  { initial: "ㄘ", final: "ㄞˋ", word: "菜", emoji: "🥬" },
  { initial: "ㄍ", final: "ㄠ", word: "糕", emoji: "🍰" },
  { initial: "ㄐ", final: "ㄧㄠˇ", word: "餃", emoji: "🥟" },
  { initial: "ㄓ", final: "ㄡ", word: "粥", emoji: "🥣" },
  { initial: "ㄉ", final: "ㄠ", word: "刀", emoji: "🔪" },
  { initial: "ㄔ", final: "ㄚ", word: "叉", emoji: "🍴" },
  { initial: "ㄔ", final: "ㄨˊ", word: "廚", emoji: "🧑‍🍳" },
  { initial: "ㄧ", final: "ㄥ", word: "鷹", emoji: "🦅" },
  { initial: "ㄌ", final: "ㄤˊ", word: "狼", emoji: "🐺" },
  { initial: "ㄏ", final: "ㄨˊ", word: "狐", emoji: "🦊" },
  { initial: "ㄒ", final: "ㄧㄥ", word: "猩", emoji: "🦍" },
  { initial: "ㄅ", final: "ㄠˋ", word: "豹", emoji: "🐆" },
  { initial: "ㄌ", final: "ㄨㄥˊ", word: "龍", emoji: "🐉" },
  { initial: "ㄈ", final: "ㄥˋ", word: "鳳", emoji: "🦚" },
  { initial: "ㄧ", final: "ㄢˋ", word: "燕", emoji: "🐦‍⬛" },
  { initial: "ㄨ", final: "ㄚ", word: "蛙", emoji: "🐸" },
  { initial: "ㄓ", final: "ㄨ", word: "蛛", emoji: "🕷️" },
  { initial: "ㄇ", final: "蚊", word: "蚊", emoji: "🦟" }, // wait this is wrong
  { initial: "ㄨ", final: "ㄣˊ", word: "蚊", emoji: "🦟" },
  { initial: "ㄧ", final: "ㄥˊ", word: "蠅", emoji: "🪰" },
  { initial: "ㄕ", final: "ㄡˇ", word: "首", emoji: "👤" },
  { initial: "ㄋ", final: "ㄠˇ", word: "腦", emoji: "🧠" },
  { initial: "ㄅ", final: "ㄟˋ", word: "背", emoji: "🔙" },
  { initial: "ㄧ", final: "ㄠ", word: "腰", emoji: "🧍" },
  { initial: "ㄊ", final: "ㄨㄟˇ", word: "腿", emoji: "🦵" },
  { initial: "ㄐ", final: "ㄧㄠˇ", word: "腳", emoji: "🦶" },
  { initial: "ㄒ", final: "ㄧㄝˊ", word: "鞋", emoji: "👟" },
  { initial: "ㄨ", final: "ㄚˋ", word: "襪", emoji: "🧦" },
  { initial: "ㄑ", final: "ㄩㄣˊ", word: "裙", emoji: "👗" },
  { initial: "ㄎ", final: "ㄨˋ", word: "褲", emoji: "👖" },
  { initial: "ㄧ", final: "ㄧ", word: "醫", emoji: "👨‍⚕️" },
  { initial: "ㄏ", final: "ㄨˋ", word: "護", emoji: "👩‍⚕️" },
  { initial: "ㄕ", final: "ㄥ", word: "生", emoji: "🧑‍🎓" },
  { initial: "ㄕ", final: "ㄧ", word: "師", emoji: "🧑‍🏫" },
  { initial: "ㄋ", final: "ㄨㄥˊ", word: "農", emoji: "🧑‍🌾" },
  { initial: "ㄍ", final: "ㄨㄥ", word: "工", emoji: "👷" },
  { initial: "ㄕ", final: "ㄤ", word: "商", emoji: "💼" },
];

// 聲調辨識用：同一拼寫、四種聲調的詞語組合
const TONE_SETS = [
  { spelling: "ㄇㄚ", tones: [ { mark: "", word: "媽媽", emoji: "👩" }, { mark: "ˊ", word: "麻煩", emoji: "😣" }, { mark: "ˇ", word: "馬路", emoji: "🐴" }, { mark: "ˋ", word: "罵人", emoji: "😠" }]},
  { spelling: "ㄧ", tones: [ { mark: "", word: "衣服", emoji: "👕" }, { mark: "ˊ", word: "移動", emoji: "🚚" }, { mark: "ˇ", word: "椅子", emoji: "🪑" }, { mark: "ˋ", word: "意思", emoji: "💭" }]},
  { spelling: "ㄨ", tones: [ { mark: "", word: "烏龜", emoji: "🐢" }, { mark: "ˊ", word: "無聊", emoji: "😴" }, { mark: "ˇ", word: "五個", emoji: "5️⃣" }, { mark: "ˋ", word: "物品", emoji: "📦" }]},
  { spelling: "ㄊㄤ", tones: [ { mark: "", word: "湯麵", emoji: "🍲" }, { mark: "ˊ", word: "糖果", emoji: "🍬" }, { mark: "ˇ", word: "躺下", emoji: "🛌" }, { mark: "ˋ", word: "燙傷", emoji: "🥵" }]},
  { spelling: "ㄈㄢ", tones: [ { mark: "", word: "翻書", emoji: "📚" }, { mark: "ˊ", word: "煩惱", emoji: "😩" }, { mark: "ˇ", word: "反對", emoji: "↩️" }, { mark: "ˋ", word: "飯糰", emoji: "🍙" }]},
  { spelling: "ㄒㄧ", tones: [ { mark: "", word: "西瓜", emoji: "🍉" }, { mark: "ˊ", word: "習字", emoji: "📝" }, { mark: "ˇ", word: "喜歡", emoji: "😊" }, { mark: "ˋ", word: "細心", emoji: "🔍" }]},
  { spelling: "ㄅㄚ", tones: [ { mark: "", word: "八個", emoji: "8️⃣" }, { mark: "ˊ", word: "拔河", emoji: "🪢" }, { mark: "ˇ", word: "靶心", emoji: "🎯" }, { mark: "ˋ", word: "爸爸", emoji: "👨" }]},
  { spelling: "ㄉㄚ", tones: [ { mark: "", word: "搭車", emoji: "🚌" }, { mark: "ˊ", word: "答案", emoji: "📋" }, { mark: "ˇ", word: "打球", emoji: "⚾" }, { mark: "ˋ", word: "大人", emoji: "🧑" }]},
  { spelling: "ㄩ", tones: [ { mark: "", word: "迂迴", emoji: "🔄" }, { mark: "ˊ", word: "魚兒", emoji: "🐟" }, { mark: "ˇ", word: "雨傘", emoji: "☂️" }, { mark: "ˋ", word: "玉米", emoji: "🌽" }]},
  { spelling: "ㄍㄨㄛ", tones: [ { mark: "", word: "鍋子", emoji: "🫕" }, { mark: "ˊ", word: "國家", emoji: "🏳️" }, { mark: "ˇ", word: "果汁", emoji: "🧃" }, { mark: "ˋ", word: "過年", emoji: "🎆" }]},
  { spelling: "ㄐㄧ", tones: [ { mark: "", word: "雞蛋", emoji: "🐔" }, { mark: "ˊ", word: "及格", emoji: "✅" }, { mark: "ˇ", word: "幾個", emoji: "❓" }, { mark: "ˋ", word: "記住", emoji: "🧠" }]},
  { spelling: "ㄓㄨ", tones: [ { mark: "", word: "豬肉", emoji: "🐷" }, { mark: "ˊ", word: "竹子", emoji: "🎋" }, { mark: "ˇ", word: "主人", emoji: "👑" }, { mark: "ˋ", word: "住家", emoji: "🏡" }]},
  { spelling: "ㄎㄜ", tones: [ { mark: "", word: "科學", emoji: "🔬" }, { mark: "ˊ", word: "殼", emoji: "🥚" }, { mark: "ˇ", word: "口渴", emoji: "🥤" }, { mark: "ˋ", word: "上課", emoji: "🏫" }]},
  { spelling: "ㄔㄜ", tones: [ { mark: "", word: "車子", emoji: "🚗" }, { mark: "ˇ", word: "扯斷", emoji: "💥" }, { mark: "ˋ", word: "徹底", emoji: "✨" }]},
  { spelling: "ㄋㄧㄡ", tones: [ { mark: "", word: "小妞", emoji: "👧" }, { mark: "ˊ", word: "牛奶", emoji: "🥛" }, { mark: "ˇ", word: "按鈕", emoji: "🔘" }, { mark: "ˋ", word: "脾氣拗", emoji: "😠" }]},
  { spelling: "ㄈㄟ", tones: [ { mark: "", word: "飛機", emoji: "✈️" }, { mark: "ˊ", word: "肥胖", emoji: "🐷" }, { mark: "ˇ", word: "匪徒", emoji: "🦹" }, { mark: "ˋ", word: "廢紙", emoji: "🗑️" }]},
  { spelling: "ㄅㄠ", tones: [ { mark: "", word: "包子", emoji: "🥟" }, { mark: "ˊ", word: "薄冰", emoji: "🧊" }, { mark: "ˇ", word: "寶貝", emoji: "👶" }, { mark: "ˋ", word: "報紙", emoji: "📰" }]},
  { spelling: "ㄕㄨ", tones: [ { mark: "", word: "書本", emoji: "📚" }, { mark: "ˊ", word: "熟肉", emoji: "🥩" }, { mark: "ˇ", word: "老鼠", emoji: "🐭" }, { mark: "ˋ", word: "大樹", emoji: "🌳" }]},
  { spelling: "ㄑㄧ", tones: [ { mark: "", word: "七個", emoji: "7️⃣" }, { mark: "ˊ", word: "騎車", emoji: "🚲" }, { mark: "ˇ", word: "起床", emoji: "🛏️" }, { mark: "ˋ", word: "汽車", emoji: "🚗" }]},
  { spelling: "ㄅㄧ", tones: [ { mark: "ˊ", word: "鼻子", emoji: "👃" }, { mark: "ˇ", word: "鉛筆", emoji: "✏️" }, { mark: "ˋ", word: "閉眼", emoji: "😌" }]},
  { spelling: "ㄏㄨㄚ", tones: [ { mark: "", word: "花朵", emoji: "🌸" }, { mark: "ˊ", word: "划船", emoji: "🚣" }, { mark: "ˋ", word: "畫畫", emoji: "🎨" }]},
  { spelling: "ㄇㄠ", tones: [ { mark: "", word: "貓咪", emoji: "🐱" }, { mark: "ˊ", word: "毛線", emoji: "🧶" }, { mark: "ˋ", word: "帽子", emoji: "🎩" }]},
  { spelling: "ㄒㄧㄤ", tones: [ { mark: "", word: "香蕉", emoji: "🍌" }, { mark: "ˊ", word: "投降", emoji: "🏳️" }, { mark: "ˇ", word: "想想", emoji: "💭" }, { mark: "ˋ", word: "大象", emoji: "🐘" }]},
  { spelling: "ㄔㄨㄤ", tones: [ { mark: "", word: "窗戶", emoji: "🪟" }, { mark: "ˊ", word: "起床", emoji: "🛏️" }, { mark: "ˇ", word: "闖關", emoji: "🏃" }, { mark: "ˋ", word: "創作", emoji: "🎨" }]},
  { spelling: "ㄧㄠ", tones: [ { mark: "", word: "妖怪", emoji: "👻" }, { mark: "ˊ", word: "搖晃", emoji: "👋" }, { mark: "ˇ", word: "咬人", emoji: "🦷" }, { mark: "ˋ", word: "吃藥", emoji: "💊" }]},
  { spelling: "ㄍㄡ", tones: [ { mark: "", word: "水溝", emoji: "💧" }, { mark: "ˇ", word: "小狗", emoji: "🐶" }, { mark: "ˋ", word: "夠了", emoji: "👌" }]},
  { spelling: "ㄉㄡ", tones: [ { mark: "", word: "都有", emoji: "👨‍👩‍👧‍👦" }, { mark: "ˇ", word: "發抖", emoji: "🥶" }, { mark: "ˋ", word: "豆子", emoji: "🫘" }]},
  { spelling: "ㄌㄨ", tones: [ { mark: "", word: "嚕車", emoji: "🚗" }, { mark: "ˊ", word: "爐子", emoji: "🔥" }, { mark: "ˇ", word: "滷味", emoji: "🍲" }, { mark: "ˋ", word: "馬路", emoji: "🛣️" }]},
  { spelling: "ㄎㄠ", tones: [ { mark: "ˇ", word: "考試", emoji: "📝" }, { mark: "ˋ", word: "手銬", emoji: "🔗" }]},
  { spelling: "ㄉㄨ", tones: [ { mark: "", word: "嘟嘴", emoji: "😗" }, { mark: "ˊ", word: "毒蛇", emoji: "🐍" }, { mark: "ˇ", word: "肚子", emoji: "🤰" }, { mark: "ˋ", word: "度數", emoji: "🌡️" }]},
  { spelling: "ㄏㄞ", tones: [ { mark: "", word: "嗨", emoji: "👋" }, { mark: "ˊ", word: "小孩", emoji: "🧒" }, { mark: "ˇ", word: "大海", emoji: "🌊" }, { mark: "ˋ", word: "害怕", emoji: "😱" }]},
  { spelling: "ㄐㄧㄠ", tones: [ { mark: "", word: "香蕉", emoji: "🍌" }, { mark: "ˊ", word: "嚼", emoji: "👄" }, { mark: "ˇ", word: "腳", emoji: "🦶" }, { mark: "ˋ", word: "睡覺", emoji: "😴" }]},
  { spelling: "ㄑㄧㄥ", tones: [ { mark: "", word: "青蛙", emoji: "🐸" }, { mark: "ˊ", word: "晴天", emoji: "☀️" }, { mark: "ˇ", word: "請進", emoji: "🚪" }, { mark: "ˋ", word: "慶祝", emoji: "🎉" }]},
  { spelling: "ㄒㄧㄝ", tones: [ { mark: "", word: "些微", emoji: "🤏" }, { mark: "ˊ", word: "鞋子", emoji: "👟" }, { mark: "ˇ", word: "寫字", emoji: "✍️" }, { mark: "ˋ", word: "謝謝", emoji: "🙏" }]},
  { spelling: "ㄓㄨㄥ", tones: [ { mark: "", word: "時鐘", emoji: "⏰" }, { mark: "ˇ", word: "腫", emoji: "🤕" }, { mark: "ˋ", word: "很重", emoji: "🏋️" }]},
  { spelling: "ㄔㄤ", tones: [ { mark: "", word: "唱歌", emoji: "🎤" }, { mark: "ˊ", word: "很長", emoji: "📏" }, { mark: "ˇ", word: "工廠", emoji: "🏭" }, { mark: "ˋ", word: "暢快", emoji: "😁" }]},
  { spelling: "ㄕㄢ", tones: [ { mark: "", word: "山", emoji: "⛰️" }, { mark: "ˇ", word: "閃電", emoji: "⚡" }, { mark: "ˋ", word: "扇子", emoji: "🪭" }]},
  { spelling: "ㄖㄢ", tones: [ { mark: "ˊ", word: "燃燒", emoji: "🔥" }, { mark: "ˇ", word: "染色", emoji: "🎨" }]},
];

// 字首範例詞語的額外候選（增加「看圖找字頭」「記憶配對」的圖案多樣性）
const INITIAL_WORD_EXTRAS = {
  "ㄅ": [{ word: "杯子", emoji: "🥤" }, { word: "蝙蝠", emoji: "🦇" }, { word: "包子", emoji: "🥟" }, { word: "冰淇淋", emoji: "🍦" }, { word: "斑馬", emoji: "🦓" }, { word: "筆", emoji: "🖊️" }, { word: "餅乾", emoji: "🍪" }, { word: "布丁", emoji: "🍮" }, { word: "冰箱", emoji: "🧊" }, { word: "白雲", emoji: "☁️" }, { word: "白菜", emoji: "🥬" }, { word: "報紙", emoji: "📰" }],
  "ㄆ": [{ word: "葡萄", emoji: "🍇" }, { word: "蘋果", emoji: "🍎" }, { word: "盤子", emoji: "🍽️" }, { word: "螃蟹", emoji: "🦀" }, { word: "跑步", emoji: "🏃" }, { word: "披薩", emoji: "🍕" }, { word: "朋友", emoji: "🤝" }, { word: "皮帶", emoji: "🎗️" }, { word: "皮鞋", emoji: "👞" }, { word: "皮球", emoji: "⚽" }, { word: "胖子", emoji: "🧍" }],
  "ㄇ": [{ word: "貓咪", emoji: "🐱" }, { word: "帽子", emoji: "🎩" }, { word: "馬", emoji: "🐴" }, { word: "麵包", emoji: "🍞" }, { word: "芒果", emoji: "🥭" }, { word: "螞蟻", emoji: "🐜" }, { word: "玫瑰", emoji: "🌹" }, { word: "蜜蜂", emoji: "🐝" }, { word: "毛巾", emoji: "🧣" }, { word: "門", emoji: "🚪" }, { word: "摩托車", emoji: "🏍️" }],
  "ㄈ": [{ word: "蜂蜜", emoji: "🍯" }, { word: "房子", emoji: "🏠" }, { word: "風車", emoji: "🎐" }, { word: "斧頭", emoji: "🪓" }, { word: "番茄", emoji: "🍅" }, { word: "飛機", emoji: "✈️" }, { word: "風箏", emoji: "🪁" }, { word: "風扇", emoji: "🌬️" }, { word: "肥皂", emoji: "🧼" }, { word: "粉筆", emoji: "🖍️" }, { word: "法語", emoji: "🇫🇷" }],
  "ㄉ": [{ word: "蛋糕", emoji: "🎂" }, { word: "燈泡", emoji: "💡" }, { word: "大象", emoji: "🐘" }, { word: "刀子", emoji: "🔪" }, { word: "電視", emoji: "📺" }, { word: "電腦", emoji: "💻" }, { word: "袋鼠", emoji: "🦘" }, { word: "地圖", emoji: "🗺️" }, { word: "地球", emoji: "🌍" }, { word: "電池", emoji: "🔋" }, { word: "豆腐", emoji: "🍲" }],
  "ㄊ": [{ word: "太陽", emoji: "☀️" }, { word: "糖果", emoji: "🍬" }, { word: "天鵝", emoji: "🦢" }, { word: "拖鞋", emoji: "🩴" }, { word: "跳舞", emoji: "💃" }, { word: "兔子", emoji: "🐰" }, { word: "桃子", emoji: "🍑" }, { word: "天空", emoji: "☁️" }, { word: "跳繩", emoji: "➰" }, { word: "梯子", emoji: "🪜" }, { word: "土豆", emoji: "🥔" }],
  "ㄋ": [{ word: "鳥",   emoji: "🐦" }, { word: "檸檬", emoji: "🍋" }, { word: "男孩", emoji: "👦" }, { word: "南瓜", emoji: "🎃" }, { word: "鈕扣", emoji: "🔘" }, { word: "牛奶", emoji: "🥛" }, { word: "女孩", emoji: "👧" }, { word: "泥土", emoji: "🟤" }, { word: "奶牛", emoji: "🐄" }, { word: "鬧鐘", emoji: "⏰" }, { word: "年糕", emoji: "🍡" }],
  "ㄌ": [{ word: "籃球", emoji: "🏀" }, { word: "梨子", emoji: "🍐" }, { word: "禮物", emoji: "🎁" }, { word: "鹿", emoji: "🦌" }, { word: "輪胎", emoji: "🛞" }, { word: "老虎", emoji: "🐯" }, { word: "駱駝", emoji: "🐪" }, { word: "拉鍊", emoji: "🤐" }, { word: "喇叭", emoji: "🎺" }, { word: "輪船", emoji: "🚢" }, { word: "溜冰", emoji: "⛸️" }],
  "ㄍ": [{ word: "鴿子", emoji: "🕊️" }, { word: "鼓",   emoji: "🥁" }, { word: "公雞", emoji: "🐓" }, { word: "狗", emoji: "🐕" }, { word: "骨頭", emoji: "🦴" }, { word: "國旗", emoji: "🇹🇼" }, { word: "果汁", emoji: "🧃" }, { word: "西瓜", emoji: "🍉" }, { word: "蘋果", emoji: "🍎" }, { word: "櫃子", emoji: "🗄️" }, { word: "高山", emoji: "⛰️" }],
  "ㄎ": [{ word: "咖啡", emoji: "☕" }, { word: "可樂", emoji: "🥤" }, { word: "恐龍", emoji: "🦖" }, { word: "孔雀", emoji: "🦚" }, { word: "烤肉", emoji: "🥩" }, { word: "卡片", emoji: "💳" }, { word: "蝌蚪", emoji: "🐸" }, { word: "褲子", emoji: "👖" }, { word: "苦瓜", emoji: "🥒" }, { word: "卡車", emoji: "🚚" }, { word: "口袋", emoji: "👝" }],
  "ㄏ": [{ word: "花",   emoji: "🌸" }, { word: "猴子", emoji: "🐵" }, { word: "紅綠燈", emoji: "🚥" }, { word: "蝴蝶", emoji: "🦋" }, { word: "火車", emoji: "🚂" }, { word: "漢堡", emoji: "🍔" }, { word: "河馬", emoji: "🦛" }, { word: "火", emoji: "🔥" }, { word: "狐狸", emoji: "🦊" }, { word: "黑板", emoji: "⬛" }, { word: "海星", emoji: "⭐" }],
  "ㄐ": [{ word: "腳",   emoji: "🦶" }, { word: "橘子", emoji: "🍊" }, { word: "剪刀", emoji: "✂️" }, { word: "警察", emoji: "👮" }, { word: "機器人", emoji: "🤖" }, { word: "雞", emoji: "🐔" }, { word: "家", emoji: "🏠" }, { word: "鏡子", emoji: "🪞" }, { word: "戒指", emoji: "💍" }, { word: "九", emoji: "9️⃣" }, { word: "鍵盤", emoji: "⌨️" }],
  "ㄑ": [{ word: "企鵝", emoji: "🐧" }, { word: "氣球", emoji: "🎈" }, { word: "鉛筆", emoji: "✏️" }, { word: "青蛙", emoji: "🐸" }, { word: "橋", emoji: "🌉" }, { word: "汽車", emoji: "🚗" }, { word: "球", emoji: "⚽" }, { word: "錢包", emoji: "👛" }, { word: "七", emoji: "7️⃣" }, { word: "茄子", emoji: "🍆" }, { word: "巧克力", emoji: "🍫" }],
  "ㄒ": [{ word: "鞋子", emoji: "👟" }, { word: "熊",   emoji: "🐻" }, { word: "香蕉", emoji: "🍌" }, { word: "星星", emoji: "⭐" }, { word: "信封", emoji: "✉️" }, { word: "西瓜", emoji: "🍉" }, { word: "雪", emoji: "❄️" }, { word: "蝦子", emoji: "🦐" }, { word: "橡皮擦", emoji: "🧽" }, { word: "吸管", emoji: "🥤" }, { word: "相機", emoji: "📷" }],
  "ㄓ": [{ word: "豬",   emoji: "🐷" }, { word: "竹子", emoji: "🎋" }, { word: "帳篷", emoji: "⛺" }, { word: "直昇機", emoji: "🚁" }, { word: "章魚", emoji: "🐙" }, { word: "蜘蛛", emoji: "🕷️" }, { word: "折紙", emoji: "🦢" }, { word: "紙", emoji: "📄" }, { word: "桌子", emoji: "🪑" }, { word: "枕頭", emoji: "🛌" }, { word: "指甲", emoji: "💅" }],
  "ㄔ": [{ word: "唱歌", emoji: "🎤" }, { word: "尺",   emoji: "📏" }, { word: "車子", emoji: "🚗" }, { word: "蟲", emoji: "🐛" }, { word: "翅膀", emoji: "🪽" }, { word: "吃飯", emoji: "🍚" }, { word: "船", emoji: "🚢" }, { word: "床", emoji: "🛏️" }, { word: "茶", emoji: "🍵" }, { word: "廚師", emoji: "🧑‍🍳" }, { word: "穿衣", emoji: "👕" }],
  "ㄕ": [{ word: "樹",   emoji: "🌳" }, { word: "手",   emoji: "🖐️" }, { word: "書", emoji: "📖" }, { word: "獅子", emoji: "🦁" }, { word: "沙發", emoji: "🛋️" }, { word: "水", emoji: "💧" }, { word: "山", emoji: "⛰️" }, { word: "石頭", emoji: "🪨" }, { word: "蛇", emoji: "🐍" }, { word: "手錶", emoji: "⌚" }, { word: "梳子", emoji: "🪮" }],
  "ㄖ": [{ word: "肉",   emoji: "🍖" }, { word: "日出", emoji: "🌅" }, { word: "忍者", emoji: "🥷" }, { word: "人", emoji: "🧑" }, { word: "軟糖", emoji: "🍬" }, { word: "熱狗", emoji: "🌭" }, { word: "日曆", emoji: "📅" }, { word: "絨毛", emoji: "🧸" }, { word: "日光", emoji: "☀️" }, { word: "燃燒", emoji: "🔥" }],
  "ㄗ": [{ word: "走路", emoji: "🚶" }, { word: "足球", emoji: "⚽" }, { word: "紫色", emoji: "🟣" }, { word: "鑽石", emoji: "💎" }, { word: "字典", emoji: "📚" }, { word: "嘴巴", emoji: "👄" }, { word: "自行車", emoji: "🚲" }, { word: "早晨", emoji: "🌄" }, { word: "雜誌", emoji: "📰" }, { word: "早餐", emoji: "🍳" }],
  "ㄘ": [{ word: "廁所", emoji: "🚽" }, { word: "彩虹", emoji: "🌈" }, { word: "刺蝟", emoji: "🦔" }, { word: "草莓", emoji: "🍓" }, { word: "蔥", emoji: "🧅" }, { word: "刺", emoji: "🌵" }, { word: "磁鐵", emoji: "🧲" }, { word: "菜", emoji: "🥬" }, { word: "擦布", emoji: "🧽" }, { word: "彩色筆", emoji: "🖍️" }],
  "ㄙ": [{ word: "傘",   emoji: "☂️" }, { word: "送禮", emoji: "🎁" }, { word: "森林", emoji: "🌲" }, { word: "鎖", emoji: "🔒" }, { word: "色彩", emoji: "🎨" }, { word: "松鼠", emoji: "🐿️" }, { word: "三", emoji: "3️⃣" }, { word: "絲帶", emoji: "🎀" }, { word: "四", emoji: "4️⃣" }, { word: "梳子", emoji: "🪮" }, { word: "酸梅", emoji: "🔴" }],
};

const OTHER_WORD_EXTRAS = {
  "ㄧ": [{ word: "一", emoji: "1️⃣" }, { word: "醫生", emoji: "👨‍⚕️" }, { word: "衣服", emoji: "👕" }, { word: "椅子", emoji: "🪑" }, { word: "音樂", emoji: "🎵" }, { word: "羊", emoji: "🐑" }, { word: "鴨子", emoji: "🦆" }, { word: "醫院", emoji: "🏥" }, { word: "爺爺", emoji: "👴" }, { word: "鸚鵡", emoji: "🦜" }, { word: "眼睛", emoji: "👁️" }],
  "ㄨ": [{ word: "五", emoji: "5️⃣" }, { word: "蝸牛", emoji: "🐌" }, { word: "烏鴉", emoji: "🐦‍⬛" }, { word: "襪子", emoji: "🧦" }, { word: "網子", emoji: "🕸️" }, { word: "烏龜", emoji: "🐢" }, { word: "碗", emoji: "🥣" }, { word: "王子", emoji: "🤴" }, { word: "舞蹈", emoji: "🩰" }, { word: "屋頂", emoji: "🏠" }, { word: "玩具", emoji: "🧸" }],
  "ㄩ": [{ word: "月亮", emoji: "🌙" }, { word: "雨傘", emoji: "☂️" }, { word: "玉米", emoji: "🌽" }, { word: "魚", emoji: "🐟" }, { word: "浴缸", emoji: "🛁" }, { word: "雲", emoji: "☁️" }, { word: "宇宙", emoji: "🌌" }, { word: "圓形", emoji: "🔴" }, { word: "羽毛", emoji: "🪶" }, { word: "運動", emoji: "🏃" }],
  "ㄚ": [{ word: "鴨子", emoji: "🦆" }, { word: "牙齒", emoji: "🦷" }, { word: "啞鈴", emoji: "🏋️" }, { word: "蠟筆", emoji: "🖍️" }, { word: "螞蟻", emoji: "🐜" }, { word: "花", emoji: "🌸" }, { word: "阿嬤", emoji: "👵" }, { word: "大", emoji: "🐘" }, { word: "爸爸", emoji: "👨" }, { word: "襪子", emoji: "🧦" }, { word: "下", emoji: "👇" }],
  "ㄛ": [{ word: "火鍋", emoji: "🍲" }, { word: "喔", emoji: "😲" }, { word: "駱駝", emoji: "🐪" }, { word: "蘋果", emoji: "🍎" }, { word: "國王", emoji: "👑" }, { word: "菠蘿", emoji: "🍍" }, { word: "撥水", emoji: "💦" }, { word: "破掉", emoji: "💔" }, { word: "摸", emoji: "🤚" }],
  "ㄜ": [{ word: "鱷魚", emoji: "🐊" }, { word: "肚子餓", emoji: "🤤" }, { word: "天鵝", emoji: "🦢" }, { word: "蛇", emoji: "🐍" }, { word: "車子", emoji: "🚗" }, { word: "鴿子", emoji: "🕊️" }, { word: "河馬", emoji: "🦛" }, { word: "喝水", emoji: "💧" }, { word: "哥哥", emoji: "👦" }, { word: "垃圾", emoji: "🗑️" }],
  "ㄝ": [{ word: "鞋子", emoji: "👞" }, { word: "葉子", emoji: "🍃" }, { word: "爺爺", emoji: "👴" }, { word: "蝴蝶", emoji: "🦋" }, { word: "蟹", emoji: "🦀" }, { word: "雪", emoji: "❄️" }, { word: "黑", emoji: "⬛" }, { word: "水餃", emoji: "🥟" }, { word: "貼紙", emoji: "🏷️" }],
  "ㄞ": [{ word: "矮子", emoji: "🧍" }, { word: "海邊", emoji: "🏖️" }, { word: "愛心", emoji: "💖" }, { word: "麥克風", emoji: "🎤" }, { word: "拍手", emoji: "👏" }, { word: "白菜", emoji: "🥬" }, { word: "袋鼠", emoji: "🦘" }, { word: "開車", emoji: "🚗" }, { word: "男孩", emoji: "👦" }, { word: "買東西", emoji: "🛍️" }],
  "ㄟ": [{ word: "飛盤", emoji: "🥏" }, { word: "黑板", emoji: "⬛" }, { word: "飛機", emoji: "✈️" }, { word: "草莓", emoji: "🍓" }, { word: "水杯", emoji: "🥤" }, { word: "妹妹", emoji: "👧" }, { word: "烏龜", emoji: "🐢" }, { word: "杯子", emoji: "🍵" }, { word: "給", emoji: "🤲" }],
  "ㄠ": [{ word: "桃子", emoji: "🍑" }, { word: "鑰匙", emoji: "🔑" }, { word: "手錶", emoji: "⌚" }, { word: "貓咪", emoji: "🐈" }, { word: "背包", emoji: "🎒" }, { word: "小鳥", emoji: "🐤" }, { word: "包子", emoji: "🥟" }, { word: "草", emoji: "🌿" }, { word: "刀子", emoji: "🔪" }, { word: "跳", emoji: "🦘" }],
  "ㄡ": [{ word: "海鷗", emoji: "🕊️" }, { word: "猴子", emoji: "🐒" }, { word: "狗", emoji: "🐕" }, { word: "球", emoji: "⚽" }, { word: "海牛", emoji: "🦭" }, { word: "肉", emoji: "🥩" }, { word: "手", emoji: "🖐️" }, { word: "頭", emoji: "👤" }, { word: "豆子", emoji: "🫘" }, { word: "樓梯", emoji: "🪜" }],
  "ㄢ": [{ word: "山", emoji: "⛰️" }, { word: "看書", emoji: "📖" }, { word: "雨傘", emoji: "☂️" }, { word: "船", emoji: "🚢" }, { word: "飯", emoji: "🍚" }, { word: "蛋", emoji: "🥚" }, { word: "盤子", emoji: "🍽️" }, { word: "藍色", emoji: "🟦" }, { word: "三", emoji: "3️⃣" }, { word: "麵包", emoji: "🍞" }],
  "ㄣ": [{ word: "門", emoji: "🚪" }, { word: "森林", emoji: "🌲" }, { word: "神仙", emoji: "🧚" }, { word: "盆栽", emoji: "🪴" }, { word: "灰塵", emoji: "💨" }, { word: "人", emoji: "🧑" }, { word: "本子", emoji: "📓" }, { word: "筆記本", emoji: "📒" }, { word: "很棒", emoji: "👍" }],
  "ㄤ": [{ word: "螳螂", emoji: "🦗" }, { word: "胖子", emoji: "🧍‍♂️" }, { word: "鋼琴", emoji: "🎹" }, { word: "糖果", emoji: "🍬" }, { word: "湯", emoji: "🥣" }, { word: "羊", emoji: "🐑" }, { word: "床", emoji: "🛏️" }, { word: "黃色", emoji: "🟨" }, { word: "上", emoji: "👆" }, { word: "狼", emoji: "🐺" }],
  "ㄥ": [{ word: "風箏", emoji: "🪁" }, { word: "企鵝", emoji: "🐧" }, { word: "蜜蜂", emoji: "🐝" }, { word: "城堡", emoji: "🏰" }, { word: "燈", emoji: "💡" }, { word: "星星", emoji: "⭐" }, { word: "冰塊", emoji: "🧊" }, { word: "朋友", emoji: "🤝" }, { word: "蘋果", emoji: "🍎" }, { word: "紅", emoji: "🟥" }],
  "ㄦ": [{ word: "耳朵", emoji: "👂" }, { word: "兒童", emoji: "🧒" }, { word: "兒子", emoji: "👦" }, { word: "鳥兒", emoji: "🐦" }, { word: "魚兒", emoji: "🐟" }, { word: "花兒", emoji: "🌸" }, { word: "二", emoji: "2️⃣" }],
};
