
const INITIAL_WORD_EXTRAS = {
  "ㄅ": [{ word: "杯子", emoji: "🥤" }, { word: "蝙蝠", emoji: "🦇" }, { word: "包子", emoji: "🥟" }, { word: "冰淇淋", emoji: "🍦" }, { word: "斑馬", emoji: "🦓" }, { word: "筆", emoji: "🖊️" }, { word: "餅乾", emoji: "🍪" }, { word: "布丁", emoji: "🍮" }],
  "ㄆ": [{ word: "葡萄", emoji: "🍇" }, { word: "蘋果", emoji: "🍎" }, { word: "盤子", emoji: "🍽️" }, { word: "螃蟹", emoji: "🦀" }, { word: "跑步", emoji: "🏃" }, { word: "披薩", emoji: "🍕" }, { word: "朋友", emoji: "🤝" }],
  "ㄇ": [{ word: "貓咪", emoji: "🐱" }, { word: "帽子", emoji: "🎩" }, { word: "馬", emoji: "🐴" }, { word: "麵包", emoji: "🍞" }, { word: "芒果", emoji: "🥭" }, { word: "螞蟻", emoji: "🐜" }, { word: "玫瑰", emoji: "🌹" }],
  "ㄈ": [{ word: "蜂蜜", emoji: "🍯" }, { word: "房子", emoji: "🏠" }, { word: "風車", emoji: "🎐" }, { word: "斧頭", emoji: "🪓" }, { word: "番茄", emoji: "🍅" }, { word: "飛機", emoji: "✈️" }, { word: "風箏", emoji: "🪁" }],
  "ㄉ": [{ word: "蛋糕", emoji: "🎂" }, { word: "燈泡", emoji: "💡" }, { word: "大象", emoji: "🐘" }, { word: "刀子", emoji: "🔪" }, { word: "電視", emoji: "📺" }, { word: "電腦", emoji: "💻" }, { word: "袋鼠", emoji: "🦘" }],
  "ㄊ": [{ word: "太陽", emoji: "☀️" }, { word: "糖果", emoji: "🍬" }, { word: "天鵝", emoji: "🦢" }, { word: "拖鞋", emoji: "🩴" }, { word: "跳舞", emoji: "💃" }, { word: "兔子", emoji: "🐰" }, { word: "桃子", emoji: "🍑" }],
  "ㄋ": [{ word: "鳥",   emoji: "🐦" }, { word: "檸檬", emoji: "🍋" }, { word: "男孩", emoji: "👦" }, { word: "南瓜", emoji: "🎃" }, { word: "鈕扣", emoji: "🔘" }, { word: "牛奶", emoji: "🥛" }, { word: "女孩", emoji: "👧" }],
  "ㄌ": [{ word: "籃球", emoji: "🏀" }, { word: "梨子", emoji: "🍐" }, { word: "禮物", emoji: "🎁" }, { word: "鹿", emoji: "🦌" }, { word: "輪胎", emoji: "🛞" }, { word: "老虎", emoji: "🐯" }, { word: "駱駝", emoji: "🐪" }],
  "ㄍ": [{ word: "鴿子", emoji: "🕊️" }, { word: "鼓",   emoji: "🥁" }, { word: "公雞", emoji: "🐓" }, { word: "狗", emoji: "🐕" }, { word: "骨頭", emoji: "🦴" }, { word: "國旗", emoji: "🇹🇼" }, { word: "果汁", emoji: "🧃" }],
  "ㄎ": [{ word: "咖啡", emoji: "☕" }, { word: "可樂", emoji: "🥤" }, { word: "恐龍", emoji: "🦖" }, { word: "孔雀", emoji: "🦚" }, { word: "烤肉", emoji: "🥩" }, { word: "卡片", emoji: "💳" }, { word: "蝌蚪", emoji: "🐸" }],
  "ㄏ": [{ word: "花",   emoji: "🌸" }, { word: "猴子", emoji: "🐵" }, { word: "紅綠燈", emoji: "🚥" }, { word: "蝴蝶", emoji: "🦋" }, { word: "火車", emoji: "🚂" }, { word: "漢堡", emoji: "🍔" }, { word: "河馬", emoji: "🦛" }],
  "ㄐ": [{ word: "腳",   emoji: "🦶" }, { word: "橘子", emoji: "🍊" }, { word: "剪刀", emoji: "✂️" }, { word: "警察", emoji: "👮" }, { word: "機器人", emoji: "🤖" }, { word: "雞", emoji: "🐔" }, { word: "家", emoji: "🏠" }],
  "ㄑ": [{ word: "企鵝", emoji: "🐧" }, { word: "氣球", emoji: "🎈" }, { word: "鉛筆", emoji: "✏️" }, { word: "青蛙", emoji: "🐸" }, { word: "橋", emoji: "🌉" }, { word: "汽車", emoji: "🚗" }, { word: "球", emoji: "⚽" }],
  "ㄒ": [{ word: "鞋子", emoji: "👟" }, { word: "熊",   emoji: "🐻" }, { word: "香蕉", emoji: "🍌" }, { word: "星星", emoji: "⭐" }, { word: "信封", emoji: "✉️" }, { word: "西瓜", emoji: "🍉" }, { word: "雪", emoji: "❄️" }],
  "ㄓ": [{ word: "豬",   emoji: "🐷" }, { word: "竹子", emoji: "🎋" }, { word: "帳篷", emoji: "⛺" }, { word: "直昇機", emoji: "🚁" }, { word: "章魚", emoji: "🐙" }, { word: "蜘蛛", emoji: "🕷️" }, { word: "折紙", emoji: "🦢" }],
  "ㄔ": [{ word: "唱歌", emoji: "🎤" }, { word: "尺",   emoji: "📏" }, { word: "車子", emoji: "🚗" }, { word: "蟲", emoji: "🐛" }, { word: "翅膀", emoji: "🪽" }, { word: "吃飯", emoji: "🍚" }, { word: "船", emoji: "🚢" }],
  "ㄕ": [{ word: "樹",   emoji: "🌳" }, { word: "手",   emoji: "🖐️" }, { word: "書", emoji: "📖" }, { word: "獅子", emoji: "🦁" }, { word: "沙發", emoji: "🛋️" }, { word: "水", emoji: "💧" }, { word: "山", emoji: "⛰️" }],
  "ㄖ": [{ word: "肉",   emoji: "🍖" }, { word: "日出", emoji: "🌅" }, { word: "忍者", emoji: "🥷" }, { word: "人", emoji: "🧑" }, { word: "軟糖", emoji: "🍬" }, { word: "熱狗", emoji: "🌭" }, { word: "日曆", emoji: "📅" }],
  "ㄗ": [{ word: "走路", emoji: "🚶" }, { word: "足球", emoji: "⚽" }, { word: "紫色", emoji: "🟣" }, { word: "鑽石", emoji: "💎" }, { word: "字典", emoji: "📚" }, { word: "嘴巴", emoji: "👄" }, { word: "自行車", emoji: "🚲" }],
  "ㄘ": [{ word: "廁所", emoji: "🚽" }, { word: "彩虹", emoji: "🌈" }, { word: "刺蝟", emoji: "🦔" }, { word: "草莓", emoji: "🍓" }, { word: "蔥", emoji: "🧅" }, { word: "刺", emoji: "🌵" }, { word: "磁鐵", emoji: "🧲" }],
  "ㄙ": [{ word: "傘",   emoji: "☂️" }, { word: "送禮", emoji: "🎁" }, { word: "森林", emoji: "🌲" }, { word: "鎖", emoji: "🔒" }, { word: "色彩", emoji: "🎨" }, { word: "松鼠", emoji: "🐿️" }, { word: "三", emoji: "3️⃣" }],
};

const OTHER_WORD_EXTRAS = {
  "ㄧ": [{ word: "一", emoji: "1️⃣" }, { word: "醫生", emoji: "👨‍⚕️" }, { word: "衣服", emoji: "👕" }, { word: "椅子", emoji: "🪑" }, { word: "音樂", emoji: "🎵" }, { word: "羊", emoji: "🐑" }, { word: "鴨子", emoji: "🦆" }],
  "ㄨ": [{ word: "五", emoji: "5️⃣" }, { word: "蝸牛", emoji: "🐌" }, { word: "烏鴉", emoji: "🐦‍⬛" }, { word: "襪子", emoji: "🧦" }, { word: "網子", emoji: "🕸️" }, { word: "烏龜", emoji: "🐢" }, { word: "碗", emoji: "🥣" }],
  "ㄩ": [{ word: "月亮", emoji: "🌙" }, { word: "雨傘", emoji: "☂️" }, { word: "玉米", emoji: "🌽" }, { word: "魚", emoji: "🐟" }, { word: "浴缸", emoji: "🛁" }, { word: "雲", emoji: "☁️" }, { word: "宇宙", emoji: "🌌" }],
  "ㄚ": [{ word: "鴨子", emoji: "🦆" }, { word: "牙齒", emoji: "🦷" }, { word: "啞鈴", emoji: "🏋️" }, { word: "蠟筆", emoji: "🖍️" }, { word: "螞蟻", emoji: "🐜" }, { word: "花", emoji: "🌸" }, { word: "阿嬤", emoji: "👵" }],
  "ㄛ": [{ word: "火鍋", emoji: "🍲" }, { word: "喔", emoji: "😲" }, { word: "駱駝", emoji: "🐪" }, { word: "蘋果", emoji: "🍎" }, { word: "國王", emoji: "👑" }, { word: "菠蘿", emoji: "🍍" }],
  "ㄜ": [{ word: "鱷魚", emoji: "🐊" }, { word: "肚子餓", emoji: "🤤" }, { word: "天鵝", emoji: "🦢" }, { word: "蛇", emoji: "🐍" }, { word: "車子", emoji: "🚗" }, { word: "鴿子", emoji: "🕊️" }, { word: "河馬", emoji: "🦛" }],
  "ㄝ": [{ word: "鞋子", emoji: "👞" }, { word: "葉子", emoji: "🍃" }, { word: "爺爺", emoji: "👴" }, { word: "蝴蝶", emoji: "🦋" }, { word: "蟹", emoji: "🦀" }, { word: "雪", emoji: "❄️" }],
  "ㄞ": [{ word: "矮子", emoji: "🧍" }, { word: "海邊", emoji: "🏖️" }, { word: "愛心", emoji: "💖" }, { word: "麥克風", emoji: "🎤" }, { word: "拍手", emoji: "👏" }, { word: "白菜", emoji: "🥬" }, { word: "袋鼠", emoji: "🦘" }],
  "ㄟ": [{ word: "飛盤", emoji: "🥏" }, { word: "黑板", emoji: "⬛" }, { word: "飛機", emoji: "✈️" }, { word: "草莓", emoji: "🍓" }, { word: "水杯", emoji: "🥤" }, { word: "妹妹", emoji: "👧" }, { word: "烏龜", emoji: "🐢" }],
  "ㄠ": [{ word: "桃子", emoji: "🍑" }, { word: "鑰匙", emoji: "🔑" }, { word: "手錶", emoji: "⌚" }, { word: "貓咪", emoji: "🐈" }, { word: "背包", emoji: "🎒" }, { word: "小鳥", emoji: "🐤" }, { word: "包子", emoji: "🥟" }],
  "ㄡ": [{ word: "海鷗", emoji: "🕊️" }, { word: "猴子", emoji: "🐒" }, { word: "狗", emoji: "🐕" }, { word: "球", emoji: "⚽" }, { word: "海牛", emoji: "🦭" }, { word: "肉", emoji: "🥩" }, { word: "手", emoji: "🖐️" }],
  "ㄢ": [{ word: "山", emoji: "⛰️" }, { word: "看書", emoji: "📖" }, { word: "雨傘", emoji: "☂️" }, { word: "船", emoji: "🚢" }, { word: "飯", emoji: "🍚" }, { word: "蛋", emoji: "🥚" }, { word: "盤子", emoji: "🍽️" }],
  "ㄣ": [{ word: "門", emoji: "🚪" }, { word: "森林", emoji: "🌲" }, { word: "神仙", emoji: "🧚" }, { word: "盆栽", emoji: "🪴" }, { word: "灰塵", emoji: "💨" }, { word: "人", emoji: "🧑" }, { word: "本子", emoji: "📓" }],
  "ㄤ": [{ word: "螳螂", emoji: "🦗" }, { word: "胖子", emoji: "🧍‍♂️" }, { word: "鋼琴", emoji: "🎹" }, { word: "糖果", emoji: "🍬" }, { word: "湯", emoji: "🥣" }, { word: "羊", emoji: "🐑" }, { word: "床", emoji: "🛏️" }],
  "ㄥ": [{ word: "風箏", emoji: "🪁" }, { word: "企鵝", emoji: "🐧" }, { word: "蜜蜂", emoji: "🐝" }, { word: "城堡", emoji: "🏰" }, { word: "燈", emoji: "💡" }, { word: "星星", emoji: "⭐" }, { word: "冰塊", emoji: "🧊" }],
  "ㄦ": [{ word: "耳朵", emoji: "👂" }, { word: "兒童", emoji: "🧒" }, { word: "兒子", emoji: "👦" }, { word: "鳥兒", emoji: "🐦" }, { word: "魚兒", emoji: "🐟" }, { word: "花兒", emoji: "🌸" }],
};

